apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-khwq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-xrot-tenant/status-quarkus-io/statusquarkusio-khwq@sha256:83f6da1c7c2b9d19c63121fa2b77e03cd957ce6c244dda64adca0a5237306c96
        name: my-java-quarkus
        resources: {}
status: {}
